In [1]:
from glove_vec import read_glove_vectors
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

In [2]:
wordembed=read_glove_vectors('./glove.6B.50d.txt')

In [3]:
wordembed['table']

array([-0.36661 ,  1.0584  , -0.65378 ,  0.17674 ,  1.0605  , -0.72541 ,
       -0.009721,  0.07969 , -0.4649  , -0.74347 , -0.64147 , -0.16837 ,
       -0.48926 ,  0.56673 ,  0.73102 ,  0.18387 ,  0.34366 , -0.19158 ,
        0.066052, -1.3434  ,  0.50813 , -0.21998 ,  0.46182 ,  0.65796 ,
       -0.19109 , -0.6428  , -0.14994 ,  0.74716 , -0.23347 , -0.16557 ,
        2.8593  ,  0.60577 , -0.63465 ,  0.45448 ,  0.14856 ,  0.53445 ,
        0.27442 ,  1.0104  ,  0.079507, -0.44915 ,  0.46796 , -0.49001 ,
       -0.20323 ,  0.65496 ,  0.16845 ,  0.50674 ,  0.62557 ,  0.071343,
        0.61898 , -0.99744 ], dtype=float32)

In [4]:
wordembed['apple']

array([ 0.52042 , -0.8314  ,  0.49961 ,  1.2893  ,  0.1151  ,  0.057521,
       -1.3753  , -0.97313 ,  0.18346 ,  0.47672 , -0.15112 ,  0.35532 ,
        0.25912 , -0.77857 ,  0.52181 ,  0.47695 , -1.4251  ,  0.858   ,
        0.59821 , -1.0903  ,  0.33574 , -0.60891 ,  0.41742 ,  0.21569 ,
       -0.07417 , -0.5822  , -0.4502  ,  0.17253 ,  0.16448 , -0.38413 ,
        2.3283  , -0.66682 , -0.58181 ,  0.74389 ,  0.095015, -0.47865 ,
       -0.84591 ,  0.38704 ,  0.23693 , -1.5523  ,  0.64802 , -0.16521 ,
       -1.4719  , -0.16224 ,  0.79857 ,  0.97391 ,  0.40027 , -0.21912 ,
       -0.30938 ,  0.26581 ], dtype=float32)

In [5]:
wordembed['apple'].shape

(50,)

In [6]:
wordembed['love']

array([-0.13886  ,  1.1401   , -0.85212  , -0.29212  ,  0.75534  ,
        0.82762  , -0.3181   ,  0.0072204, -0.34762  ,  1.0731   ,
       -0.24665  ,  0.97765  , -0.55835  , -0.090318 ,  0.83182  ,
       -0.33317  ,  0.22648  ,  0.30913  ,  0.026929 , -0.086739 ,
       -0.14703  ,  1.3543   ,  0.53695  ,  0.43735  ,  1.2749   ,
       -1.4382   , -1.2815   , -0.15196  ,  1.0506   , -0.93644  ,
        2.7561   ,  0.58967  , -0.29473  ,  0.27574  , -0.32928  ,
       -0.201    , -0.28547  , -0.45987  , -0.14603  , -0.69372  ,
        0.070761 , -0.19326  , -0.1855   , -0.16095  ,  0.24268  ,
        0.20784  ,  0.030924 , -1.3711   , -0.28606  ,  0.2898   ],
      dtype=float32)

In [7]:
wordembed['sex']

array([-0.010419,  0.18859 , -1.1103  , -0.1153  ,  0.41355 ,  1.6054  ,
        0.20117 , -0.88146 ,  0.41256 ,  0.95368 , -0.18311 , -0.30528 ,
        0.29189 , -0.10752 ,  1.4091  , -0.17546 , -0.75133 , -0.14834 ,
        0.3885  ,  0.079413,  0.22707 ,  1.2332  ,  0.29273 ,  1.3166  ,
       -0.49709 , -1.7793  ,  0.056008, -0.397   ,  0.51418 , -0.31688 ,
        2.3976  ,  0.31263 , -0.44624 , -1.1556  , -0.28933 , -0.080372,
       -0.043744, -0.89217 , -0.48708 , -0.60101 , -0.36962 ,  0.20775 ,
        0.519   ,  1.3062  ,  0.54721 , -0.77457 ,  0.10109 , -0.66229 ,
        0.16455 ,  0.51965 ], dtype=float32)

In [8]:
wordembed['is']

array([ 6.1850e-01,  6.4254e-01, -4.6552e-01,  3.7570e-01,  7.4838e-01,
        5.3739e-01,  2.2239e-03, -6.0577e-01,  2.6408e-01,  1.1703e-01,
        4.3722e-01,  2.0092e-01, -5.7859e-02, -3.4589e-01,  2.1664e-01,
        5.8573e-01,  5.3919e-01,  6.9490e-01, -1.5618e-01,  5.5830e-02,
       -6.0515e-01, -2.8997e-01, -2.5594e-02,  5.5593e-01,  2.5356e-01,
       -1.9612e+00, -5.1381e-01,  6.9096e-01,  6.6246e-02, -5.4224e-02,
        3.7871e+00, -7.7403e-01, -1.2689e-01, -5.1465e-01,  6.6705e-02,
       -3.2933e-01,  1.3483e-01,  1.9049e-01,  1.3812e-01, -2.1503e-01,
       -1.6573e-02,  3.1200e-01, -3.3189e-01, -2.6001e-02, -3.8203e-01,
        1.9403e-01, -1.2466e-01, -2.7557e-01,  3.0899e-01,  4.8497e-01],
      dtype=float32)

In [24]:
apple=wordembed['apple'].reshape(1,-1)
orange=wordembed['orange'].reshape(1,-1)


sex=wordembed['sex'].reshape(-1,1)

In [25]:
avg=np.sum(np.array([apple,orange,sex]),axis=0)/3

In [26]:
cosine_similarity(avg,apple)

array([[0.88594365],
       [0.8939791 ],
       [0.63472545],
       [0.8733328 ],
       [0.87641084],
       [0.57650274],
       [0.89373803],
       [0.6924168 ],
       [0.8765467 ],
       [0.75228983],
       [0.86253405],
       [0.83875173],
       [0.889343  ],
       [0.87444615],
       [0.6257977 ],
       [0.8638466 ],
       [0.7267387 ],
       [0.8683106 ],
       [0.87969947],
       [0.8922885 ],
       [0.89295757],
       [0.67334205],
       [0.8892807 ],
       [0.6504579 ],
       [0.79346824],
       [0.49690586],
       [0.8910551 ],
       [0.8180329 ],
       [0.8602284 ],
       [0.83624905],
       [0.42264202],
       [0.8876934 ],
       [0.80615586],
       [0.6238712 ],
       [0.84213036],
       [0.87811524],
       [0.88251525],
       [0.6896273 ],
       [0.79599506],
       [0.766604  ],
       [0.82442796],
       [0.89357597],
       [0.8593423 ],
       [0.6532806 ],
       [0.8539681 ],
       [0.7205669 ],
       [0.89316   ],
       [0.750

In [27]:
cosine_similarity(avg,orange)

array([[0.86800724],
       [0.83903754],
       [0.76301694],
       [0.8745125 ],
       [0.7813956 ],
       [0.3666766 ],
       [0.8364738 ],
       [0.80084556],
       [0.7816987 ],
       [0.58468443],
       [0.87570435],
       [0.8725172 ],
       [0.81555396],
       [0.8742291 ],
       [0.42487133],
       [0.87568194],
       [0.8216037 ],
       [0.8753759 ],
       [0.7889448 ],
       [0.8576583 ],
       [0.8309315 ],
       [0.48284608],
       [0.8153409 ],
       [0.45468786],
       [0.85635895],
       [0.6624053 ],
       [0.8607882 ],
       [0.8662495 ],
       [0.748788  ],
       [0.8718928 ],
       [0.19424757],
       [0.8101981 ],
       [0.86173815],
       [0.7555632 ],
       [0.8732899 ],
       [0.8729943 ],
       [0.8707123 ],
       [0.7990946 ],
       [0.85747117],
       [0.8434768 ],
       [0.86842835],
       [0.8350993 ],
       [0.74714506],
       [0.45813438],
       [0.7374001 ],
       [0.8179864 ],
       [0.85448647],
       [0.834

In [21]:
cosine_similarity(avg,sex)

ValueError: Incompatible dimension for X and Y matrices: X.shape[1] == 50 while Y.shape[1] == 1