In [1]:
from glove_vec import read_glove_vectors
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

In [2]:
word_embedding_dict = read_glove_vectors("/home/vasu/all_projects/CB/glove.6B.50d.txt")

In [3]:
word_embedding_dict["table"]

array([-0.36661 ,  1.0584  , -0.65378 ,  0.17674 ,  1.0605  , -0.72541 ,
       -0.009721,  0.07969 , -0.4649  , -0.74347 , -0.64147 , -0.16837 ,
       -0.48926 ,  0.56673 ,  0.73102 ,  0.18387 ,  0.34366 , -0.19158 ,
        0.066052, -1.3434  ,  0.50813 , -0.21998 ,  0.46182 ,  0.65796 ,
       -0.19109 , -0.6428  , -0.14994 ,  0.74716 , -0.23347 , -0.16557 ,
        2.8593  ,  0.60577 , -0.63465 ,  0.45448 ,  0.14856 ,  0.53445 ,
        0.27442 ,  1.0104  ,  0.079507, -0.44915 ,  0.46796 , -0.49001 ,
       -0.20323 ,  0.65496 ,  0.16845 ,  0.50674 ,  0.62557 ,  0.071343,
        0.61898 , -0.99744 ], dtype=float32)

In [4]:
word_embedding_dict["table"].shape

(50,)

## ODD ONE OUT

In [18]:
apple = word_embedding_dict["sleeping"].reshape(1,-1)
mango = word_embedding_dict["playing"].reshape(1,-1)
banana = word_embedding_dict["dancing"].reshape(1,-1)
kiwi = word_embedding_dict["moving"].reshape(1,-1)
chair = word_embedding_dict["bat"].reshape(1,-1) 

In [19]:
avg_vec = np.sum(np.array([apple,mango,banana,kiwi,chair]), axis=0)/5

In [20]:
cosine_similarity(avg_vec,apple)

array([[0.68821794]], dtype=float32)

In [21]:
cosine_similarity(avg_vec,mango)

array([[0.8414831]], dtype=float32)

In [22]:
cosine_similarity(avg_vec,banana)

array([[0.7845105]], dtype=float32)

In [23]:
cosine_similarity(avg_vec,kiwi)

array([[0.7077991]], dtype=float32)

In [24]:
cosine_similarity(avg_vec,chair)

array([[0.64428294]], dtype=float32)