# Numpy Array

1.Numpy is a numperical python library used to work with arrays.

2. Numpy arrays are faster than the list because the arrangement of the elements are continuous in the computer memory.

3. Numpy array's are faster than list.

In [ ]:
!pip3 install numpy

In [1]:
import numpy as np

In [7]:
list1=[1,2,3,4,"inder",False]
print("the list is------->",list1)
array=np.array(list1)
print("the array is ------->",array)



the list is-------> [1, 2, 3, 4, 'inder', False]
the array is -------> ['1' '2' '3' '4' 'inder' 'False']


# Multi-Dimensional Array

Data in the arrays are stored in a tabular arrangement.

In [17]:
list1=[1,3,5,10]
list2=[2,4,6,8]
list3=[2,3,5,7]


array=np.array([list1,list2,list3])
print("Shape of my array",array.shape)

Shape of my array (3, 4)


In [11]:
array[0][2]

5

In [15]:
np.array(list1)

array([1, 3, 5, 7])

# Ranks in Numpy Array

The rank of an array would be the number of axis it has

For example a 1-d Array has rank 1.


In [18]:
np.zeros([4,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

The shape of an array is number of elements in each dimension



# Reshaping in Arrays

# Reshaping changes the shapes of an array

By reshaping we can add or remove dimension from an array

In [32]:
arr=np.array([1,3,5,7,9,11,13,15,17,19,21,23])
arr.shape

(12,)

In [35]:
arr.reshape(2,6)

array([[ 1,  3,  5,  7,  9, 11],
       [13, 15, 17, 19, 21, 23]])

In [36]:
arr.reshape(6,2)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19],
       [21, 23]])

In [37]:
arr.reshape(3,4)

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [44]:
# Q.1 Find the position of 4333 in this array.
arr=np.array([[1,2,3,4,5,6,7],[1,15,21,32,21,4333,12]])

arr[1][-2]
arr[-1][-2]
arr[1][5]

4333

In [47]:
arr[-1][-2]

4333

# Joining the Arrays

If there are two array we will combine them into single one

In [49]:
arr1=np.array([1,11,111])
arr2=np.array([2,22,222])

resultant_array=np.concatenate((arr1,arr2))
resultant_array

array([  1,  11, 111,   2,  22, 222])

In [58]:
arr1=np.array([[1,3],[4,5]])
arr2=np.array([[5,7],[14,15]])

resultant_array=np.concatenate((arr1,arr2),axis=1)
resultant_array

array([[ 1,  3,  5,  7],
       [ 4,  5, 14, 15]])

In [63]:
arr1=np.array([[1,3],[4,5]])
arr2=np.array([[5,7],[14,15]])

resultant_array=np.stack( (arr1,arr2),axis=1)
resultant_array

array([[[ 1,  3],
        [ 5,  7]],

       [[ 4,  5],
        [14, 15]]])

# horizontal stack is used to stack along rows and vertical stack is used to stack along columns

In [65]:
arr1=np.array([1,11,111])
arr2=np.array([2,22,222])
horizontal_stack=np.hstack((arr1,arr2))
horizontal_stack

array([  1,  11, 111,   2,  22, 222])

In [66]:
arr1=np.array([1,11,111])
arr2=np.array([2,22,222])
horizontal_stack=np.vstack((arr1,arr2))
horizontal_stack

array([[  1,  11, 111],
       [  2,  22, 222]])

# Splitting the Numpy arrays

Splitting you can see is reverse of joining

In [74]:
arr1=np.array([1,11,111,32,122222,32,21,32,21])
np.array_split(arr1,3)

[array([  1,  11, 111]), array([    32, 122222,     32]), array([21, 32, 21])]

In [78]:
np.array([1  ,3 , 5])

array([1, 3, 5])

In [75]:
arr_2d=np.array([[1,2],[3,4],[5,6],[7,8],[8,9]])
arr_2d

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [8, 9]])

# Searching in Arrays

In [76]:
arr1=np.array([1,11,111,32,122222,32,21,32,21])
np.where(arr1==122222)

(array([4], dtype=int64),)

In [77]:
np.where(arr1%2==0)

(array([3, 4, 5, 7], dtype=int64),)

In [79]:
np.sort(arr1) #this is used to sort array in ascending order

array([     1,     11,     21,     21,     32,     32,     32,    111,
       122222])

In [87]:
-np.sort(-arr1)  #this is used to sort array in descending order

array([122222,    111,     32,     32,     32,     21,     21,     11,
            1])

In [89]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [102]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [100]:
arr=np.ones(5)
arr.astype(int)


array([1, 1, 1, 1, 1])

In [91]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [94]:
for i in range(1,10):
    print(i)

1
2
3
4
5
6
7
8
9


In [92]:
np.arange(3,7)

array([3, 4, 5, 6])

In [103]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [104]:
np.linspace(2,3,num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [113]:
np.linspace(2,3,num=5,endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [105]:
np.linspace(2,3,num=5,endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [107]:
x_axis=np.linspace(1,10,num=5)
y_axis=np.linspace(11,20,num=5)


In [108]:
x_axis

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [109]:
y_axis

array([11.  , 13.25, 15.5 , 17.75, 20.  ])

In [174]:
np.linspace(1,9,5)

array([1., 3., 5., 7., 9.])

# numpy.logspace

In [117]:
np.logspace(2,3,num=5,base=2)

array([4.        , 4.75682846, 5.65685425, 6.72717132, 8.        ])

In [123]:
x=np.arange(16).reshape((4,-1))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [127]:
np.diag(x,k=3)

array([3])

# The exponential function calcualtes the exponential power of all elements

In [118]:
arr1=np.array([1,2,3,4])
np.exp(arr1)


array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

# Random number generation

In [130]:
#Uniform Distribution
np.random.rand(2,3)

array([[0.27615115, 0.19109096, 0.6519224 ],
       [0.07826724, 0.34174171, 0.66661254]])

In [131]:
#Uniform Distribution
np.random.randn(2,3)

array([[ 0.78181655, -0.17259924,  2.18127359],
       [-0.65044707,  0.66143825,  0.16367238]])

In [137]:
np.random.randint(1,10)

3

In [149]:
def guess_game():
    flag=True
    money=1000
    while flag:
        input_no=int(input("Please insert a number"))
        random_no=np.random.randint(1,10)
        if money==0:
            print("Please add more money in your game")
            break
        if input_no==random_no:
            flag=False
            money=money+100000000000000000000
            print("You won a lottery of ------>",money)
            print("You won the game")
        else:
            money=money-200
            print("Try again")

In [150]:
guess_game()

Please insert a number5
Try again
Please insert a number1
Try again
Please insert a number2
Try again
Please insert a number3
Try again
Please insert a number1
Try again
Please insert a number2
Please add more money in your game


In [151]:
arr1=np.array([1,11,111,32,122222,32,21,32,21])
arr1.max()

122222

In [153]:
arr1.min()

1

In [154]:
x=np.arange(16).reshape((4,-1))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [155]:
x[1,3]

7

# Slicing in arrays

In [156]:
arr=np.arange(0,12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [158]:
arr[1:3]

array([1, 2])

In [160]:
arr[1:10:2]

array([1, 3, 5, 7, 9])

In [161]:
x=np.arange(16).reshape((4,-1))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [168]:
x[:3,:1]

array([[0],
       [4],
       [8]])

In [170]:
arr1=np.arange(16).reshape((4,-1))
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [169]:
arr2=np.arange(16,32).reshape((4,-1))
arr2

array([[16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [171]:
arr1*arr2 #multiplication of array

array([[  0,  17,  36,  57],
       [ 80, 105, 132, 161],
       [192, 225, 260, 297],
       [336, 377, 420, 465]])

In [172]:
np.sqrt(2)

1.4142135623730951

In [173]:
np.log10(3)

0.47712125471966244

In [175]:
arr1=np.arange(16).reshape((4,-1))
arr1


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [179]:
arr1.flat[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])