In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
a=np.array([1,3,5])
b=np.array([1,2,3])

a*b

array([ 1,  6, 15])

In [5]:
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [6]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [7]:
np.random.rand(4,2,5)

array([[[0.74030027, 0.68789314, 0.12436257, 0.88148083, 0.51894607],
        [0.0350294 , 0.18146424, 0.39803999, 0.76023851, 0.65387059]],

       [[0.49915369, 0.36489296, 0.32752738, 0.40409451, 0.53991703],
        [0.97404114, 0.11588022, 0.94946243, 0.07037872, 0.82074454]],

       [[0.12559999, 0.66724974, 0.53953353, 0.50254557, 0.96218817],
        [0.9297726 , 0.67825784, 0.43703867, 0.48601778, 0.29601784]],

       [[0.70611029, 0.41890884, 0.1844651 , 0.86279278, 0.923562  ],
        [0.51106061, 0.06591055, 0.8651741 , 0.54261393, 0.71898442]]])

In [8]:
##random integer values
np.random.randint(-4,8,size=(3,3))

array([[ 4,  6, -2],
       [-2,  7,  7],
       [ 1, -4,  2]])

In [17]:
output=np.ones((5,5))
print(output)
z=np.zeros((3,3))
z[1,1]=9
print(z)

output[1:-1,1:-1]=z
print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [19]:
#vertical stack

v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
#horizontal stack
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

np.hstack([v1,v2,v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
#load the data
np.genfromtxt('data.txt',delimite=',')
